export const GET_GAME_PAGINATION_SUCCESS = 'GET_GAME_SUCCESS';
export const GET_GAME_INPUT_SUCCESS = 'GET_GAME_INPUT_SUCCESS';
export const GET_GAME_API_BD_BY_ID_SUCCESS = 'GET_GAME_API_BD_BY_ID_SUCCESS';
export const GET_GAME_BY_NAME_SUCCESS = 'GET_GAME_BY_NAME_SUCCESS';
export const GET_GAME_GENRES_SUCCESS = 'GET_GAME_GENRES_SUCCESS';




//////////////////////////////
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_ERROR = 'CREATE_GAME_ERROR';

export const DELETE_GAME_SUCCESS = 'DELETE_GAME_SUCCESS';
export const DELETE_GAME_ERROR = 'DELETE_GAME_ERROR';


export const MODIFY_GAME_SUCCESS = 'MODIFY_GAME_SUCCESS';
export const MODIFY_GAME_ERROR = 'MODIFY_GAME_ERROR';


